import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { ScrollToTop } from "./components/ScrollTop";
import SearchHandler from "./components/SearchHandler";
import MusicContextProvider from "@/context/MusicContextProvider";
import PlayerCover from "./components/Player";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Stremio-NM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <MusicContextProvider>
          <ScrollToTop />
          <Navbar />
          <SearchHandler>{children}</SearchHandler>
          <div className="fixed bottom-0 left-0 w-full z-50">
            <PlayerCover />
          </div>
        </MusicContextProvider>
      </body>
    </html>
  );
}
